[build]
  publish = "site"
  command = "mkdocs build"

[build.environment]
  PYTHON_VERSION = "3.8"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "site/.cache"
    ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  MKDOCS_ENV = "production"

[context.deploy-preview.environment]
  MKDOCS_ENV = "preview"